name: CI

on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  zip_job:
    name: Compress the resource pack
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.5

      - name: Zip Release
        uses: TheDoctor0/zip-release@0.6.0
        with:
          # Filename for archive
          filename: Ryo-Server-Pack.zip
          # Base path for archive files
          path: .
          # Working directory before zipping
          directory: /home/runner/work/Ryo-Server-Pack/Ryo-Server-Pack
          # List of excluded files / directories
          exclusions: ''
          # Tool to use for archiving
          type: zip
      - name: Release
        uses: ncipollo/release-action@v1.8.10
        with:
          artifacts: /home/runner/work/Ryo-Server-Pack/Ryo-Server-Pack/
          bodyFile: Ryo-Server-Pack.zip
          
